name: Checks

on: [push, workflow_call]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coveralls coverage[toml]
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m coverage run -m unittest discover -s tests -v
    - name: Coverage report
      run: |
        python -m coverage report 